import { title } from 'process'
import {
  Adsnot,
  Bankaccountnotlinked,
  Catlog,
  Config,
  Creative,
  Getfeat,
  Icon10thimg,
  Icon11thimg,
  Icon12thimg,
  Icon3rdimg,
  Icon4thimg,
  Icon5thimg,
  Icon6thimg,
  Icon7thimg,
  Icon8thimg,
  Icon9thimg,
  Iconactive,
  Iconapointment,
  Iconappointment2,
  Iconneeds,
  Icononapoit,
  Icononbording,
  Icononcamp,
  Iconondigit,
  Icononeasy,
  Icononget,
  Icononpromo,
  Icononreview,
  Icononsals,
  Icononstuido,
  Iconright,
  Iconsales,
  Iconvisits,
  Msgnot,
  Noapoitment,
  Noeasy,
  Nomonthlytargetset,
  Nopromo,
  Nosale,
  NotFullyOnboarded,
  OffPeakhoursnotset,
  Partnot,
  Product,
  Staffnotadded,
  SubscriptionOverdue,
} from './Icon1'

export const navItems = [
  {
    url: '/dashboard',
    icon: Icon3rdimg,
    title: 'Dashboard',
  },
  {
    url: '/planner',
    icon: Icon4thimg,
    title: 'Planner',
  },
  {
    url: '/insights',
    icon: Icon5thimg,
    title: 'Insights',
  },
  {
    url: '/partner',
    icon: Icon6thimg,
    title: 'Partner',
  },
  {
    url: '/appointment',
    icon: Icon7thimg,
    title: 'Appointment',
  },
  {
    url: '/sales',
    icon: Icon8thimg,
    title: 'Sales',
  },
  {
    url: '/team',
    icon: Icon9thimg,
    title: 'Team',
  },
  {
    url: '/report',
    icon: Icon10thimg,
    title: 'Report',
  },
  {
    url: '/training',
    icon: Icon11thimg,
    title: 'Training',
  },
  {
    url: '/settings',
    icon: Icon12thimg,
    title: 'Settings',
  },
]
export const cardsDetail = [
  {
    icon: <Iconapointment />,
    title: 'Registered vs Assigned',
    heading: '90 / 270',
    righticon: <Iconright />,
    para: '+9%',
    percentage: '+12%',
  },
  {
    icon: <Iconactive />,
    title: 'Active  vs Registered',
    heading: '21 / 90',
    righticon: <Iconright />,
    para: '+2',
    percentage: '+8%',
  },
  {
    icon: <Iconvisits />,
    title: 'Visits this month',
    heading: '50 / 250',
    righticon: <Iconright />,
    para: '+2%',
    percentage: '+8%',
  },
  {
    icon: <Iconsales />,
    title: 'Sales',
    heading: '150 / 100',
    righticon: <Iconright />,
    para: '+9%',
    percentage: '+6%',
  },
  {
    icon: <Iconappointment2 />,
    title: 'Appointment',
    heading: '75 / 100',
    righticon: <Iconright />,
    para: '+9%',
    percentage: '+2%',
  },
  {
    icon: <Iconneeds />,
    title: 'Needs attention',
    heading: '15 / 21',
    righticon: <Iconright />,
    para: '+2%',
    percentage: '+2%',
  },
]
export const performDetail = [
  {
    Icon: <Icononbording />,
    para1: 'Onboarding',
    para2: '+34%',
    para3: '12/20',
    Value: 82,
  },
  {
    Icon: <Icononapoit />,
    para1: 'Appointment',
    para2: '+6%',
    para3: '14/20',
    Value: 60,
  },
  {
    Icon: <Icononsals />,
    para1: 'Sales',
    para2: '+22%',
    para3: '16/20',
    Value: 50,
  },
  {
    Icon: <Icononcamp />,
    para1: 'Campaign Message',
    para2: '-5%',
    para3: '8/20',
    Value: 40,
  },
  {
    Icon: <Icononpromo />,
    para1: 'Promo Code',
    para2: '+60%',
    para3: '10/20',
    Value: 70,
  },
  {
    Icon: <Icononget />,
    para1: 'Get Featured',
    para2: '+12%',
    para3: '15/20',
    Value: 30,
  },
  {
    Icon: <Iconondigit />,
    para1: 'Digital Ads',
    para2: '+6%',
    para3: '11/20',
    Value: 80,
  },
  {
    Icon: <Icononstuido />,
    para1: 'Creative Studio',
    para2: '+12%',
    para3: '15/20',
    Value: 90,
  },
  {
    Icon: <Icononeasy />,
    para1: 'Easy Share',
    para2: '+3%',
    para3: '9/20',
    Value: 60,
  },
  {
    Icon: <Icononreview />,
    para1: 'Review',
    para2: '+3%',
    para3: '9/20',
    Value: 50,
  },
]
export const TaskDetail = [
  {
    Icon: <Nosale />,
    title: 'No Sale (7days)',
    pera: '28 salons',
  },
  {
    Icon: <Noeasy />,
    title: 'No Easy Share (30 days)',
    pera: '28 salons',
  },
  {
    Icon: <Noapoitment />,
    title: 'No Appointment(7 days)',
    pera: '17 salons',
  },
  {
    Icon: <Creative />,
    title: 'Creative not used (30 d)',
    pera: '17 salons',
  },
  {
    Icon: <Catlog />,
    title: 'Catalog Incomplete',
    pera: '13 salons',
  },
  {
    Icon: <Adsnot />,
    title: 'Ads not used (60 days)',
    pera: '13 salons',
  },
  {
    Icon: <Config />,
    title: 'Configure Offer Incomplete',
    pera: '21 salons',
  },
  {
    Icon: <Msgnot />,
    title: 'Msg Center not used (30 d)',
    pera: '21 salons',
  },
  {
    Icon: <Nopromo />,
    title: 'No Promo code (60 days )',
    pera: '21 salons',
  },
  {
    Icon: <Getfeat />,
    title: 'Get Feat. not used (60 days)',
    pera: '21 salons',
  },
  {
    Icon: <Product />,
    title: 'Product not added ',
    pera: '21 salons',
  },

  {
    Icon: <Partnot />,
    title: 'Partner not visited (30 days)',
    pera: '21 salons',
  },
]
export const CriticalDetail = [
  {
    Icon: <NotFullyOnboarded />,
    title: 'Not Fully Onboarded',
    pera: '14 salons',
  },
  {
    Icon: <OffPeakhoursnotset />,
    title: 'Off-Peak hours not set',
    pera: '8 salons',
  },
  {
    Icon: <Bankaccountnotlinked />,
    title: 'Bank account not linked',
    pera: '10 salons',
  },
  {
    Icon: <Nomonthlytargetset />,
    title: 'No monthly target set',
    pera: '11 salons',
  },
  {
    Icon: <Staffnotadded />,
    title: 'Staff not added / incomplete',
    pera: '13 salons',
  },
  {
    Icon: <SubscriptionOverdue />,
    title: 'Subscription Overdue',
    pera: '5 salons',
  },
]
