import { count } from "console";
import { GreenRightIcon, LocationIcon, PhoneSmallIcon, RedWrongtIcon, ShowPassIcon } from "./Icon2";

export const loginFormData = [
  {
    label: "Email",
    type: "email",
    id: "email",
    placeholder: "ex. dasalon@gmail.com",
  },
  {
    label: "Password",
    type: "text", //change to pass after comple project
    id: "password",
    placeholder: "Password",
    icon: <ShowPassIcon />,
  },
];

export const criticalFiltersData = [
  { title: "Today" },
  { title: "Yesterday" },
  { title: "Next 7 days" },
  { title: "Next 30 days" },
  { title: "This Month" },
  { title: "Next Month" },
  { title: "This year" },
];

export const saloneData = [
  {
    id: 1,
    saloneName: [
      {
        img: "/assest/png/salone-small-img.png",
        name: "Chroma Lounge",
      },
    ],
    add: "281 Madison Street, SoHo District, NY",
    health: "80",
    issue: [{ issu1: "Power outage", issu2: "Water leak" }],
    staff: "15",
    onboarding: <GreenRightIcon />,
    bankAcc: <GreenRightIcon />,
    monthlyTarget: <RedWrongtIcon />,
    subscription: "active",
    lastVisit: "3 days ago",
    nextVisit: "July 10, 2025",
    tcName: "Ayesha Sharma",
    rmName: "Rhea Malhotra",
    feName: "Neha Singh",
    action: "...",
  },
];

export const criticalData = [
  {
    head: [
      { title: "Salone Name" },
      { title: "Address" },
      { title: "Health" },
      { title: "Issue" },
      { title: "Staff" },
      { title: "OnBoarding" },
      { title: "Bank Acc." },
      { title: "Monthly Target" },
      { title: "Subscription" },
      { title: "Last Visit" },
      { title: "Next Visit" },
      { title: "TC Name" },
      { title: "RM Name" },
      { title: "FE Name" },
      { title: "Action" },
    ],
    body: [
      {
        id: 1,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "Chroma Lounge",
          },
        ],
        add: "281 Madison Street, SoHo District, NY",
        health: "80",
        issue: [{ issu1: "2", issu2: "3" }],
        staff: "15",
        onboarding: <GreenRightIcon />,
        bankAcc: <GreenRightIcon />,
        monthlyTarget: <RedWrongtIcon />,
        subscription: "active",
        lastVisit: "3 days ago",
        nextVisit: "July 10, 2025",
        tcName: "Ayesha Sharma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
        sidebarData: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "Glamour Glow Studio",
            nextVisit: ": 23 June ",
            lastVisit: " 28 June",
            contacte: [
              {
                icon: <LocationIcon />,
                title: "123 Sparkle Ave, Glam City",
                path: "#",
              },
              {
                icon: <PhoneSmallIcon />,
                title: "55523-32324",
                path: "tel:55523-32324",
              },
            ],
            condetions: [
              { count: "Critical : 6" },
              {},
              { count: "Growth : 4" },
              {},
              { count: "Health : 8" },
            ],
            ownerName: " John Walley",
            ownerNo: " 23246-93902",
            manager: " Esther Howard",
            managerNo: " 78363-47438",
            fe: " Aditi Singh",
            feNo: " 32456-39432",
            rm: "  23348-32948",
            rmNo: " 78363-47438",
            tc: "  Priya Kumari",
            tcNo: " 84950-34859",
            actionData: [
              {
                heaing: "Visit on April 10th, 2024",
                persone: "by Ajay Singh (FE)",
                pera: [
                  { stronText: "Overall Score:", text: " 30/50" },
                  {
                    stronText: "Remarks: ",
                    text: " Showed keen interest in CRM and membership features. Demo scheduled.",
                  },
                ],
              },
              {
                heaing: "Visit on April 10th, 2024",
                persone: "by Ajay Singh (FE)",
                pera: [
                  {
                    stronText: "Reason: ",
                    text: " Task from previous visit not completed",
                  },
                  {
                    stronText: "Remarks: ",
                    text: " Showed keen interest in CRM and membership features. Demo scheduled.",
                  },
                ],
              },
              {
                heaing: "Visit on April 10th, 2024",
                persone: "by Ajay Singh (FE)",
                pera: [
                  { stronText: "Overall Score:", text: " 30/50" },
                  {
                    stronText: "Remarks: ",
                    text: " Showed keen interest in CRM and membership features. Demo scheduled.",
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 2,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "Maison Glow",
          },
        ],
        add: "Luxe Layers Lounge, 1285",
        health: "12",
        issue: [{ issu1: "3", issu2: "1" }],
        staff: "5",
        onboarding: <RedWrongtIcon />,
        bankAcc: <RedWrongtIcon />,
        monthlyTarget: <GreenRightIcon />,
        subscription: "expired",
        lastVisit: "11 days ago",
        nextVisit: "Aug 10 ,2025",
        tcName: "Meera Sharma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
      {
        id: 3,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "The Gilded Comb",
          },
        ],
        add: "The Styling Suite, 45 Ke....",
        health: "25",
        issue: [{ issu1: "3", issu2: "2" }],
        staff: "3",
        onboarding: <RedWrongtIcon />,
        bankAcc: <RedWrongtIcon />,
        monthlyTarget: <RedWrongtIcon />,
        subscription: "due",
        lastVisit: "6 days ago",
        nextVisit: "July 14 ,2025",
        tcName: "Ritika Verma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
      {
        id: 4,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "Chroma Lounge",
          },
        ],
        add: "281 Madison Street, SoHo District, NY",
        health: "80",
        issue: [{ issu1: "2", issu2: "3" }],
        staff: "15",
        onboarding: <GreenRightIcon />,
        bankAcc: <GreenRightIcon />,
        monthlyTarget: <RedWrongtIcon />,
        subscription: "active",
        lastVisit: "3 days ago",
        nextVisit: "July 10, 2025",
        tcName: "Ayesha Sharma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
      {
        id: 5,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "Maison Glow",
          },
        ],
        add: "Luxe Layers Lounge, 1285",
        health: "12",
        issue: [{ issu1: "3", issu2: "1" }],
        staff: "5",
        onboarding: <RedWrongtIcon />,
        bankAcc: <RedWrongtIcon />,
        monthlyTarget: <GreenRightIcon />,
        subscription: "expired",
        lastVisit: "11 days ago",
        nextVisit: "Aug 10 ,2025",
        tcName: "Meera Sharma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
      {
        id: 6,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "The Gilded Comb",
          },
        ],
        add: "The Styling Suite, 45 Ke....",
        health: "25",
        issue: [{ issu1: "3", issu2: "2" }],
        staff: "3",
        onboarding: <RedWrongtIcon />,
        bankAcc: <RedWrongtIcon />,
        monthlyTarget: <RedWrongtIcon />,
        subscription: "due",
        lastVisit: "6 days ago",
        nextVisit: "July 14 ,2025",
        tcName: "Ritika Verma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
      {
        id: 7,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "Chroma Lounge",
          },
        ],
        add: "281 Madison Street, SoHo District, NY",
        health: "80",
        issue: [{ issu1: "2", issu2: "3" }],
        staff: "15",
        onboarding: <GreenRightIcon />,
        bankAcc: <GreenRightIcon />,
        monthlyTarget: <RedWrongtIcon />,
        subscription: "active",
        lastVisit: "3 days ago",
        nextVisit: "July 10, 2025",
        tcName: "Ayesha Sharma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
      {
        id: 8,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "Maison Glow",
          },
        ],
        add: "Luxe Layers Lounge, 1285",
        health: "12",
        issue: [{ issu1: "3", issu2: "1" }],
        staff: "5",
        onboarding: <RedWrongtIcon />,
        bankAcc: <RedWrongtIcon />,
        monthlyTarget: <GreenRightIcon />,
        subscription: "expired",
        lastVisit: "11 days ago",
        nextVisit: "Aug 10 ,2025",
        tcName: "Meera Sharma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
      {
        id: 9,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "The Gilded Comb",
          },
        ],
        add: "The Styling Suite, 45 Ke....",
        health: "25",
        issue: [{ issu1: "3", issu2: "2" }],
        staff: "3",
        onboarding: <RedWrongtIcon />,
        bankAcc: <RedWrongtIcon />,
        monthlyTarget: <RedWrongtIcon />,
        subscription: "due",
        lastVisit: "6 days ago",
        nextVisit: "July 14 ,2025",
        tcName: "Ritika Verma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
      {
        id: 10,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "Chroma Lounge",
          },
        ],
        add: "281 Madison Street, SoHo District, NY",
        health: "80",
        issue: [{ issu1: "2", issu2: "3" }],
        staff: "15",
        onboarding: <GreenRightIcon />,
        bankAcc: <GreenRightIcon />,
        monthlyTarget: <RedWrongtIcon />,
        subscription: "active",
        lastVisit: "3 days ago",
        nextVisit: "July 10, 2025",
        tcName: "Ayesha Sharma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
      {
        id: 11,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "Maison Glow",
          },
        ],
        add: "Luxe Layers Lounge, 1285",
        health: "12",
        issue: [{ issu1: "3", issu2: "1" }],
        staff: "5",
        onboarding: <RedWrongtIcon />,
        bankAcc: <RedWrongtIcon />,
        monthlyTarget: <GreenRightIcon />,
        subscription: "active",
        lastVisit: "11 days ago",
        nextVisit: "Aug 10 ,2025",
        tcName: "Meera Sharma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
      {
        id: 12,
        saloneName: [
          {
            img: "/assest/png/salone-small-img.png",
            name: "The Gilded Comb",
          },
        ],
        add: "The Styling Suite, 45 Ke....",
        health: "25",
        issue: [{ issu1: "3", issu2: "2" }],
        staff: "3",
        onboarding: <RedWrongtIcon />,
        bankAcc: <RedWrongtIcon />,
        monthlyTarget: <RedWrongtIcon />,
        subscription: "due",
        lastVisit: "6 days ago",
        nextVisit: "July 14 ,2025",
        tcName: "Ritika Verma",
        rmName: "Rhea Malhotra",
        feName: "Neha Singh",
        action: "...",
      },
    ],
  },
];


export const mudalData = [
  {
    img: "/assest/png/glamour-glow-studio.png",
    name: "Glamour Glow Studio",
    nextVisit: ": 23 June ",
    lastVisit: " 28 June",
    contacte: [
      {
        icon: <LocationIcon />,
        title: "123 Sparkle Ave, Glam City",
        path: "#",
      },
      {
        icon: <PhoneSmallIcon />,
        title: "55523-32324",
        path: "tel:55523-32324",
      },
    ],
    condetions: [
      { count: "Critical : 6" },
      {},
      { count: "Growth : 4" },
      {},
      { count: "Health : 8" },
    ],

    tabItems: [
      { value: "last-visit", label: "Last Visit Summary" },
      { value: "catalog-staff", label: "Catalog & Staff" },
      { value: "offers", label: "Offers" },
      { value: "promote-usage", label: "Promote Usage" },
      { value: "client-engagement", label: "Client Engagement" },
      { value: "setup", label: "Set up" },
      { value: "submit", label: "Submit" },
    ],
  },
];


