'use client'
// import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import '@/app/globals.css'
import { GlobalProvider } from '@/provider/GlobalProvider'

const manrope = Manrope({
  variable: '--font-Manrope',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
import { SidebarProvider } from '@/components/ui/sidebar' // ✅ ShadCN se
import { AppSidebar } from '@/components/common/AppSidebar'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <GlobalProvider>
        <body className={`${manrope.variable}  antialiased`}>
          <SidebarProvider>{children}</SidebarProvider>
        </body>
      </GlobalProvider>
    </html>
  )
}
