'use client'
// import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import '@/app/globals.css'
import { GlobalProvider } from '@/provider/GlobalProvider'

const manrope = Manrope({
  variable: '--font-Manrope',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <GlobalProvider>
        <body className={`${manrope.variable}  antialiased   `}>
          {children}
        </body>
      </GlobalProvider>
    </html>
  )
}
